// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCup3qATF96hdXwxTBBOXeZT8ooX-pxpMs',
    appId: '1:368715655730:web:e4f39e12abede5aa5b2a2b',
    messagingSenderId: '368715655730',
    projectId: 'topupapps-54efa',
    authDomain: 'topupapps-54efa.firebaseapp.com',
    storageBucket: 'topupapps-54efa.appspot.com',
    measurementId: 'G-C8E0F0813C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5EORTgfjsyou_vSH1_UI3HYKwv_WDyLA',
    appId: '1:368715655730:android:4053c6f312a5539a5b2a2b',
    messagingSenderId: '368715655730',
    projectId: 'topupapps-54efa',
    storageBucket: 'topupapps-54efa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaXxNPI8POw3ZlLScHDoYEvQtR6BeLk1M',
    appId: '1:368715655730:ios:94649ae9ebee899c5b2a2b',
    messagingSenderId: '368715655730',
    projectId: 'topupapps-54efa',
    storageBucket: 'topupapps-54efa.appspot.com',
    androidClientId: '368715655730-ggse7d3kmtrj9og5v2cp5rqq5kfu2qll.apps.googleusercontent.com',
    iosClientId: '368715655730-9eoukvtbas0q3q4p8ft4b8vd62ed5829.apps.googleusercontent.com',
    iosBundleId: 'com.codmshop.bd.gamestopup',
  );
}
